apiVersion: v1
appVersion: v1.0.0

description: proof-management-service

name: proof-management-service

version: 1.0.2

dependencies:
  - name: library
    version: 1.0.0
    repository: "https://gitlab.com/api/v4/projects/40471958/packages/helm/stable/"
